# THOSE VALUES DEPENDES ON SCREEN RESOLUTION AND EMULATOR POSITION

#IS THIS BOT RUNNING ON A RETINA DISPLAY COMPUTER ?
IS_RETINA_DISPLAY = False
RESOLUTION_FACTOR = 2 if IS_RETINA_DISPLAY else 1
RETINA_POS_FACTOR = 2 if IS_RETINA_DISPLAY else 1
RETINA_SIZE_FACTOR = 4 if IS_RETINA_DISPLAY else 2

# COMPONENTS COORDINATES
HOME_BUTTON = (45, 790)
PROFILE_BUTTON = (397, 790)
SIGNUP_BUTTON = (220, 439)
USERNAME_BUTTON = (218, 300)
EMAIL_BUTTON = (312, 140)
LOGIN_BUTTON = (213, 350)
OPTION_BUTTON = (421, 100)
LOGOUT_BUTTON = (296, 491)
DISCOVER_BUTTON = (130, 790)
SEARCH_BAR = (195, 95)
SEARCH_BUTTON = (407, 100)
FIRST_USER_IN_LIST = (98, 227)
FOLLOWERS_BUTTON = (220, 269)
TOP_BACK_BUTTON = (20, 100)
FIRST_HASHTAG_IN_LIST = (70, 220)
FIRST_VIDEO_IN_HASHTAG_RESULT = (70, 330)
SECOND_VIDEO_IN_HASHTAG_RESULT = (220, 330)
THIRD_VIDEO_IN_HASHTAG_RESULT = (350, 330)
COMMENT_BAR_ON_FEED = (170, 798)
SEND_COMMENT_BUTTON = (418, 760)
ANDROID_BACK_BUTTON = (156, 831)
COMMENT_BUTTON = (419, 579)
FIRST_USER_IN_FOLLOWERS_LIST = (110, 185)
FIRST_POST_ON_USER_FEED = (77, 491)
LIKE_BUTTON = (415, 526)

# POSITIONS - ALEATORY ON TIKYBOT POSITION
INITIAL_MOUSE_POSITION_X = 109
INITIAL_MOUSE_POSITION_Y = 432


# CAPTCHA VERIFICATION
CAPTCHA_MIN_X = 160
CAPTCHA_MAX_X = 338
CAPTCHA_MIN_Y = 360
CAPTCHA_MAX_Y = 505
MOUSE_MOVE_SPEED = 2
PUZZLE_IMAGES_COUNT = 11

# FOR GET USERNAME AND USER ID FROM FOLLOWERS LIST
REGION_X_OFFSET = 290
REGION_Y_OFFSET_USERID = 7
REGION_Y_OFFSET_USERNAME = 11
REGION_WIDTH = 250
REGION_HEIGHT = 24

# BUTTONS PATH NAME
BUTTON_HOME = "res/home_button.png"
BUTTON_ADD_ACCOUNT = "res/add_account_button.png"
BUTTON_CAPTCHA_REFRESH = "res/refresh_captcha.png"
BUTTON_LOGOUT = "res/logout_button.png"
BUTTON_FOLLOW = "res/follow_button.png"
ICON_MINI_PLAY = "res/mini_play.png"

# VALUES THAT MAYBE DOES NOT NEED TO CHANGE
DEFAULT_CONFIDENCE = 0.8
CAPTCHA_ATTEMPT_COUNT = 3
CLICK_IMAGE_DELAY = 2
CLICK_DELAY = 2
WAIT_FOR_CAPTCHA = 3
CAPTCHA_CONFIDENCE = 0.6
DEFAULT_SCROLL_SIZE = 10
RANDOM_MIN_WAIT_WATCH_VIDEO = 15
RANDOM_MAX_WAIT_WATCH_VIDEO = 20
WAIT_FOR_HASHTAG_RESULTS = 3
WAIT_FOR_SEARCH_USER_RESULTS = 3
WAIT_FOR_FOLLOWERS_RESULT = 3
DEBUG_MOUSE_UPDATE_DELAY = 2